{
    'name': 'Habin',
    'version': '1.0',
    'depends': ['base', 'mail'],
    'author': 'Javhaa',
    'category': 'Booking house',
    'description': 'Custom Airbnb-like module for house listings, bookings, and payments.',
    'data': [
        'security/ir.model.access.csv',
        'views/habin_guest_view.xml',
        'views/habin_host_view.xml',
        'views/habin_listing_view.xml',
        'views/habin_order_view.xml',
        'views/habin_order_detail_view.xml',
        'views/habin_payment_view.xml',
        'views/habin_review_view.xml',
        'views/habin_menu.xml',  
        'views/habin_order_detail_wizard_view.xml',
        'views/habin_order_create_wizard_view.xml',
        'views/habin_order_progress_view.xml',
        'views/generate_invoice_wizard_view.xml',
        'views/report_invoice_template.xml',
        'views/mail_template.xml',
    ],
    'installable': True,
    'application': True,
}
